import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nowizo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <SidebarProvider> */}
          <div className="flex w-screen bg-black">
            <main className="w-screen">{children}</main>
            <Toaster position="top-center"  toastOptions={{
            className: 'bg-gray-950 text-white text-center',
          }}/>
          </div>
        {/* </SidebarProvider> */}
      </body>
    </html>
  );
}
